# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  branches:
    include:
    - master
pr: none
   
pool:
  vmImage: 'macOS-latest'

variables:
- group: 'variable_group'

resources: 
  repositories: 
    - repository: andriod_templates
      type: github
      name: Dayanandachari/andriod_templates
      endpoint: 'Dayanandachari'

steps:
- template: build_andriod_template.yml@andriod_templates
  parameters:
    jdkVersionOption: '$(jdkVersionOption)'
    Build_version: '$(Build_version)' 
 
  
- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: Copy .apk files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  displayName: Publish artifacts

- template: build_andriod_template.yml@andriod_templates
  parameters:
    Key_password: '$(Key_password)'
    keystore_password: '$(keystore_password)'


- template: build_andriod_template.yml@andriod_templates
  parameters:
    serverEndpoint: '$(serverEndpoint)'
    appSlug: '$(appSlug)'
    releaseNotesInput: '$(releaseNotesInput)'
    distributionGroupId: '$(distributionGroupId)'
